<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ForgotPwd</name>
   <tag></tag>
   <elementGuidId>6e7130ae-624b-4842-b358-072abc6d8c9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-header/nz-layout[1]/nz-content[1]/app-login[1]/div[2]/div[1]/form[1]/nz-form-item[2]/div[1]/div[2]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-header/nz-layout[1]/nz-content[1]/app-login[1]/div[2]/div[1]/form[1]/nz-form-item[2]/div[1]/div[2]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
