<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RegisterBtn</name>
   <tag></tag>
   <elementGuidId>1f88f35c-5471-4993-90c2-32b0969e5f93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-header/nz-layout[1]/nz-content[1]/app-register[1]/section[1]/div[1]/div[1]/div[2]/form[1]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-header/nz-layout[1]/nz-content[1]/app-register[1]/section[1]/div[1]/div[1]/div[2]/form[1]/button[1]</value>
   </webElementProperties>
</WebElementEntity>
