<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MaxNumOfFilesAllowedPer_CF</name>
   <tag></tag>
   <elementGuidId>10ca91e5-703c-43e5-bd83-3a07eb8b6c05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@formcontrolname='NUMBER_OF_FILES_PER_COMPRESSED_FILE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@formcontrolname='NUMBER_OF_FILES_PER_COMPRESSED_FILE']</value>
   </webElementProperties>
</WebElementEntity>
