<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MaxNumOfDailySubms</name>
   <tag></tag>
   <elementGuidId>f30c8df2-4a74-4334-803d-4e9ac8600152</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@formcontrolname='DAILY_SUBMISSIONS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@formcontrolname='DAILY_SUBMISSIONS']</value>
   </webElementProperties>
</WebElementEntity>
