<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectThardCheckBox</name>
   <tag></tag>
   <elementGuidId>33db7931-f14d-44a0-be10-0ec791c53790</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr[5]/td[1]/label[1]/span[1]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr[5]/td[1]/label[1]/span[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
