<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectAllCheckBox</name>
   <tag></tag>
   <elementGuidId>b7914ec8-1f07-47c9-bc9f-496ca53db838</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//thead/tr[1]/th[1]/span[1]/div[1]/span[1]/label[1]/span[1]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//thead/tr[1]/th[1]/span[1]/div[1]/span[1]/label[1]/span[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
