<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ForgotPwd_Email_Input</name>
   <tag></tag>
   <elementGuidId>eba8a338-90c6-41e8-b272-2abc8578157e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-header/nz-layout[1]/nz-content[1]/app-forgot-password[1]/div[2]/div[1]/form[1]/nz-form-item[1]/nz-form-control[1]/div[1]/span[1]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-header/nz-layout[1]/nz-content[1]/app-forgot-password[1]/div[2]/div[1]/form[1]/nz-form-item[1]/nz-form-control[1]/div[1]/span[1]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
