<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LoginBtn</name>
   <tag></tag>
   <elementGuidId>b16245b6-18b0-4eab-b36a-a18a67ae4166</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-header/nz-layout[1]/nz-content[1]/app-login[1]/div[2]/div[1]/form[1]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-header/nz-layout[1]/nz-content[1]/app-login[1]/div[2]/div[1]/form[1]/button[1]</value>
   </webElementProperties>
</WebElementEntity>
