<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UserName_Email_Input</name>
   <tag></tag>
   <elementGuidId>457199af-dcad-4cd5-b365-95b6fe08c6fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-header/nz-layout[1]/nz-content[1]/app-login[1]/div[2]/div[1]/form[1]/nz-form-item[1]/nz-form-control[1]/div[1]/span[1]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-header/nz-layout[1]/nz-content[1]/app-login[1]/div[2]/div[1]/form[1]/nz-form-item[1]/nz-form-control[1]/div[1]/span[1]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
