<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SiteInspectTermsOfUse_CheckBox</name>
   <tag></tag>
   <elementGuidId>5e5710c3-3437-4797-83e2-b52ff3550ea6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class='ant-checkbox-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class='ant-checkbox-inner']</value>
   </webElementProperties>
</WebElementEntity>
